version: "3.8"

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /opt/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - backend_whenwemeet-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - /opt/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - backend_whenwemeet-network
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  backend_whenwemeet-network:
    external: true
