version: "3.8"

services:

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    image: whenwemeet-prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    networks:
      - backend_whenwemeet-network
    restart: unless-stopped

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    image: whenwemeet-grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend_whenwemeet-network
    environment:
      - GF_SERVER_ROOT_URL=https://whenwemeet.site/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  backend_whenwemeet-network:
    external: true
