spring:

  ## DB설정
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: ${SPRING_DATA_REDIS_JEDIS_POOL_MAX_ACTIVE}
          max-idle: ${SPRING_DATA_REDIS_JEDIS_POOL_MAX_IDLE}
          min-idle: ${SPRING_DATA_REDIS_JEDIS_POOL_MIN_IDLE}
          max-wait: ${SPRING_DATA_REDIS_JEDIS_POOL_MAX_WAIT}

  jwt:
    name:
      access-token: ${SPRING_JWT_NAME_ACCESS_TOKEN}
      refresh-token: ${SPRING_JWT_NAME_REFRESH_TOKEN}
      guest-token: ${SPRING_JWT_NAME_GUEST_TOKEN}
    expiration:
      access-token: ${SPRING_JWT_EXPIRATION_ACCESS_TOKEN}
      refresh-token: ${SPRING_JWT_EXPIRATION_REFRESH_TOKEN}
      guest-token: ${SPRING_JWT_EXPIRATION_GUEST_TOKEN}
    secret: ${SPRING_JWT_SECRET}
    issuer: ${SPRING_JWT_ISSUER}

  login:
    target-uri: ${SPRING_LOGIN_TARGET_URI}

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE}

  ## JPA 설정
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        show_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
        jdbc:
          batch_size: ${SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE}
    defer-datasource-initialization: ${SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION}

  ## OAuth 로그인 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: ${KAKAO_CLIENT_NAME}
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: ${KAKAO_AUTHORIZATION_GRANT_TYPE}
            client-authentication-method: ${KAKAO_CLIENT_AUTHENTICATION_METHOD}
            scope: ${KAKAO_SCOPE}

          google:
            client-name: ${GOOGLE_CLIENT_NAME}
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: ${GOOGLE_AUTHORIZATION_GRANT_TYPE}
            scope: ${GOOGLE_SCOPE}

        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: ${KAKAO_USER_NAME_ATTRIBUTE}

          google:
            authorization-uri: ${GOOGLE_AUTHORIZATION_URI}
            token-uri: ${GOOGLE_TOKEN_URI}
            user-info-uri: ${GOOGLE_USER_INFO_URI}
            user-name-attribute: ${GOOGLE_USER_NAME_ATTRIBUTE}


logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
    org.hibernate: ${LOGGING_LEVEL_ORG_HIBERNATE}

## Actuator & Monitoring 설정
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: ${MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED}
    health:
      enabled: ${MANAGEMENT_ENDPOINT_HEALTH_ENABLED}
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS}
    metrics:
      enabled: ${MANAGEMENT_ENDPOINT_METRICS_ENABLED}
  prometheus:
    metrics:
      export:
        enabled: ${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED}